imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MainBundle/Resources/config/services.yml" }
    - { resource: "@ShopBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    images_directory: '%kernel.root_dir%/../web/uploads'
    groupe_images: '%kernel.root_dir%/../web/Groupe/img'
    profile_images: '%kernel.root_dir%/../web/photoprofil'


framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: MainBundle\Entity\Member
    from_email:
        address:        erandopi14@gmail.com
        sender_name:    Password Resetting



hwi_oauth:
    connect:
        confirmation: true
        registration_form: fos_user.registration.form.factory
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookID
    resource_owners:
        #facebook Access
        facebook:
            type: facebook
            client_id: 1822296591373106
            client_secret: fa533b0ba4212428ffb832058614f3bd
            scopre: "email"
vich_uploader:
    db_driver: orm
    mappings:
        product_image:
                    uri_prefix:         /uploads
                    upload_destination: '%kernel.root_dir%/../web/uploads'
                    inject_on_load:     false
                    delete_on_remove:   true
        product_cv:
             uri_prefix:         /cv
             upload_destination: '%kernel.root_dir%/../web/cv'
        publication_cv:
             uri_prefix:         /publication
             upload_destination: '%kernel.root_dir%/../web/publication'
        photo_profil:
              uri_prefix:         /photoprofil
              upload_destination: '%kernel.root_dir%/../web/photoprofil'
        groupecouverture:
                    uri_prefix:         /group
                    upload_destination: '%kernel.root_dir%/../web/group'
                    inject_on_load:     true
                    delete_on_remove:   true
ewz_recaptcha:
    public_key:  here_is_your_public_key
    private_key: here_is_your_private_key
    # Not needed as "%kernel.default_locale%" is the default value for the locale key
    locale_key:  %kernel.default_locale%
mgilet_notification:
    notification_class: MainBundle\Entity\Notification
#Knp paginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:foundation_v5_pagination.html.twig # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Group\GroupBundle\Entity\Comment
            thread: Group\GroupBundle\Entity\Thread
    service:
          sorting:
            default: date_asc

assetic:
    bundles: [ "FOSCommentBundle" ]


