guide_guide:
    resource: "@GuideGuideBundle/Resources/config/routing.yml"
    prefix:   /guide

group_group:
    resource: "@GroupGroupBundle/Resources/config/routing.yml"
    prefix:   /group

shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /shop

administration_admin:
    resource: "@AdministrationAdminBundle/Resources/config/routing.yml"
    prefix:   /
main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect
facebook_login:
    path: /connect/check-facebook
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /noti
belousovr:
    resource: "@belousovChatBundle/Controller"
    type:     annotation
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
