administration_admin:
    resource: "@AdministrationAdminBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"