
group_group_add_new:
    path:     /groupeadd
    defaults: { _controller: GroupGroupBundle:Group:addgroup }

group_group_membres:
    path:     /membres/{id}
    defaults: { _controller: GroupGroupBundle:Group:membreGroupe}

group_group_photos:
    path:     /photos/{id}
    defaults: { _controller: GroupGroupBundle:Group:photosGroupe}
group_new:
    path:     /{id}
    defaults: { _controller: GroupGroupBundle:Group:newGroupe}
pub_delete:
    path:     /delete/{idpub}/{id}
    defaults: { _controller: GroupGroupBundle:Group:deletepub}
pub_update:
    path:     /update/{idpub}/{id}
    defaults: { _controller: GroupGroupBundle:Group:updatepub}
add_comment:
    path:     /addcomment/{idpub}/{id}
    defaults: { _controller: GroupGroupBundle:Group:addcomment}
group_add_member:
    path:     /add/{idm}/{id}
    defaults: { _controller: GroupGroupBundle:Group:addmembergroup}


addmember:
    path:     /addm/{idm}/{id}
    defaults: { _controller: GroupGroupBundle:Group:ajouterMembre}


