administration_admin_login:
    path:     /cp
    defaults: { _controller: AdministrationAdminBundle:Default:login }
administration_admin_homepage:
    path:     /cp/
    defaults: { _controller: AdministrationAdminBundle:Default:index }

administration_admin_boite-reception:
    path:     /cp/email
    defaults: { _controller: AdministrationAdminBundle:Default:boiteReception }

administration_admin_calendrier:
    path:     /cp/calendrier
    defaults: { _controller: AdministrationAdminBundle:Default:calendrier }

administration_admin_liste_demande:
    path:     /cp/listedemande
    defaults: { _controller: AdministrationAdminBundle:Default:listedemande }

administration_admin_liste_guide:
    path:     /cp/listeguide
    defaults: { _controller: AdministrationAdminBundle:Default:listeguide }

administration_admin_liste_membre:
    path:     /cp/listemembre
    defaults: { _controller: AdministrationAdminBundle:Default:listemembre }

administration_admin_liste_publication:
    path:     /cp/listepub
    defaults: { _controller: AdministrationAdminBundle:Default:listpubl }
administration_admin_stat:
    path:     /cp/stat
    defaults: { _controller: AdministrationAdminBundle:Default:stat}
supprimer_guide:
    path:     /cp/supprmer/{idguide}
    defaults: { _controller: AdministrationAdminBundle:Default:deleteGuide}
bannir_membre:
    path:     /cp/bannir/{id}
    defaults: { _controller: AdministrationAdminBundle:Default:bannirMembre}